version: "3"
services:
  redis:
    image: redis:6.2.3
    container_name: lnjoying-redis
    #restart: always
    ports:
     - "6379:6379"
    command: redis-server --requirepass hello
    networks:
      - lnjoying-bridge
  postgres:
    image: postgres:13.3
    container_name: lnjoying-postgres
    #restart: always
    ports:
     - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "abcabc"
      POSTGRES_DB: "justicedb"
    volumes:
      - /home/lnjoying/mount/postgre/init:/docker-entrypoint-initdb.d/
      - /home/lnjoying/mount/postgre/data:/var/lib/postgresql
    networks:
      - lnjoying-bridge
  nginx:
    image: nginx:latest
    container_name: lnjoying-nginx
    #restart: always
    network_mode: "host"
    volumes:
      - /home/lnjoying/mount/nginx/web:/root/web
      - /home/lnjoying/mount/nginx/nginx.conf:/etc/nginx/nginx.conf
  servicecomb:
    image: servicecomb/service-center
    container_name: lnjoying-servicecomb
    #restart: always
    ports:
      - "30100:30100"
    networks:
      - lnjoying-bridge
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "50m"
  justice_cloud:
    image: lnjoying/lnjoying-cloud:v1.0.0
    container_name: lnjoying-cloud
    #restart: always
    network_mode: "host"
    volumes:
      - /home/lnjoying/mount/justice/config:/root/justice_config
      - /home/lnjoying/mount/justice/logs:/root/justice_cloud/logs
      - /home/lnjoying/mount/justice/out:/root/justice_cloud/out
    depends_on:
      - redis
      - postgres
      - nginx
      - servicecomb
networks:
  lnjoying-bridge:
    driver: bridge
