!com.lnjoying.justice.api.config.NodeConfig
node_name: justice_admin
region_id: admin
node_id: FFAHX27SuEWT9yQPiFACsQCvjMkCa6vFrjf4z
private_key: 2fGJgWhsXTbgsEjxnmPis1DkUxrFNuUDfPAhk8mAPGRdxqQUDhzcs67dEF
