#!/bin/bash
export APP_HOME=~/lnjoying_cloud
export CONFIG_BASE_HOME=${HOME}/lnjoying_config
export ETC_HOME=${CONFIG_BASE_HOME}/etc
export LOG_CFG_HOME=${CONFIG_BASE_HOME}/log
export BIN_HOME=${APP_HOME}/bin
export LOG_OUT=${APP_HOME}/out
export LOG_DIR=${APP_HOME}/logs
export BASE_OPT="-Dfile.encoding=UTF-8 -Dlj_config=$ETC_HOME"
export RESOURCE_OPTS=$RESOURCE_OPTS
export POSTGRES_DB_NAME="justicedb"
export POSTGRES_IP="127.0.0.1"
export JUSTICE_DEBUG=true
# servicecomb
if [ $SC_ADDRESS ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -Dservicecomb.service.registry.address=$SC_ADDRESS"
fi
if [ $INSPECTOR ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -Dservicecomb.inspector.enabled=$INSPECTOR"
else
  RESOURCE_OPTS="$RESOURCE_OPTS -Dservicecomb.inspector.enabled=false"
fi
#redis
if [ $REDIS_HOST ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DREDIS_HOST=$REDIS_HOST"
fi
if [ $REDIS_PORT ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DREDIS_PORT=$REDIS_PORT"
fi
if [ $REDIS_PASSWORD ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DREDIS_PASSWORD=$REDIS_PASSWORD"
fi
#postgres
if [ $POSTGRES_IP ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DPOSTGRES_IP=$POSTGRES_IP"
fi
if [ $POSTGRES_PORT ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DPOSTGRES_PORT=$POSTGRES_PORT"
fi
if [ $POSTGRES_DB_NAME ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DPOSTGRES_DB_NAME=$POSTGRES_DB_NAME"
fi
if [ $POSTGRES_USERNAME ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DPOSTGRES_USERNAME=$POSTGRES_USERNAME"
fi
if [ $POSTGRES_PASSWORD ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DPOSTGRES_PASSWORD=$POSTGRES_PASSWORD"
fi
#mongo
if [ $MONGO_HOST ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DMONGO_HOST=$MONGO_HOST"
fi
if [ $MONGO_PORT ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DMONGO_PORT=$MONGO_PORT"
fi
if [ $MONGO_DBNAME ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DMONGO_DBNAME=$MONGO_DBNAME"
fi
if [ $MONGO_USERNAME ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DMONGO_USERNAME=$MONGO_USERNAME"
fi
if [ $MONGO_PASSWORD ];then
  RESOURCE_OPTS="$RESOURCE_OPTS -DMONGO_PASSWORD=$MONGO_PASSWORD"
fi