#!/bin/bash

if [ x$JUSTICE_DEBUG == xtrue ];then
    ps -aef | grep 'com.justice\|com.lnjoying' | grep -v grep | awk '{print $2 " "  $NF}'
else
    ps -aef | grep 'com.justice\|com.lnjoying' | grep -v grep | awk '{print $2 " "  $NF}'
fi
